version: "3"
services:
  # docker compose up -d <----
  # docker-compose up -d <----
  # docker-compose: https://docs.docker.com/compose/install/

  # docker compose down
  app:
    build: ./
    volumes:
      - ./:/var/www/
      - ./public:/var/www/html
  nginx:
    image: nginx:1.21.1-alpine
    ports:
      - "8080:80" # http://localhost:8080
    volumes:
      - ./public:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - app