name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, intl
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: xdebug
          tools: php-cs-fixer, phpunit

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}


      - name: Check php errors
        uses: michaelw90/PHP-Lint@master

      - name: PHP Code Style (phpcs)
        uses: chindit/actions-phpcs@master

      - name: PWd
        run: |
          pwd

      - name: Check web.php
        run: |
          php -l lesson-content/simple-site-demo/routes/web.php
